name: Eclipse build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and push image
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
    with:
      image_name: eclipse
