name: rpm-build image

on:
  schedule:
    - cron: "0 7 * * *" # 07:00 UTC every day
  workflow_dispatch:

jobs:
  build:
    name: Build and push image
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        fedora_release: [41, 42]
    with:
      image_name: rpm-build
      fedora_release: ${{ matrix.fedora_release }}
      build_package: false
